import type { BodyArea, BodyPoint, Exercise, PainAssessment, ProgressLog } from './types';

export const areaLabels: Record<BodyArea, string> = {
  neck: 'Cuello',
  shoulders: 'Hombros',
  upper_back: 'Espalda alta',
  lower_back: 'Espalda baja',
  hips: 'Cadera',
  knees: 'Rodillas',
  ankles: 'Tobillos',
};

export const bodyPoints: BodyPoint[] = [
  { id: 'neck', label: 'Cuello', area: 'neck', x: 50, y: 18 },
  { id: 'left-shoulder', label: 'Hombro izquierdo', area: 'shoulders', x: 35, y: 28 },
  { id: 'right-shoulder', label: 'Hombro derecho', area: 'shoulders', x: 65, y: 28 },
  { id: 'upper-back', label: 'Espalda alta', area: 'upper_back', x: 50, y: 39 },
  { id: 'lower-back', label: 'Espalda baja', area: 'lower_back', x: 50, y: 55 },
  { id: 'left-hip', label: 'Cadera izquierda', area: 'hips', x: 42, y: 66 },
  { id: 'right-hip', label: 'Cadera derecha', area: 'hips', x: 58, y: 66 },
  { id: 'left-knee', label: 'Rodilla izquierda', area: 'knees', x: 42, y: 82 },
  { id: 'right-knee', label: 'Rodilla derecha', area: 'knees', x: 58, y: 82 },
  { id: 'ankles', label: 'Tobillos', area: 'ankles', x: 50, y: 95 },
];

export const exerciseLibrary: Exercise[] = [
  {
    id: 'neck-1',
    name: 'Deslizamiento del nervio mediano',
    area: 'neck',
    category: 'Neurodinamia',
    durationSeconds: 45,
    sets: 2,
    reps: '8 repeticiones',
    difficulty: 'Baja',
    description: 'Desliza el tejido neural desde cuello hacia brazo para reducir sensacion de compresion.',
    therapeuticGoal: 'Liberar tension neural cervical y disminuir dolor que baja hacia hombro, brazo o mano.',
    image: '/exercise-diagrams/median-nerve-glide.svg',
    videoDemo: 'median',
    startingPosition: 'De pie o sentado, hombro relajado y brazo a un lado.',
    steps: ['Abre el brazo a 45 grados con palma hacia arriba.', 'Extiende suavemente muneca y dedos.', 'Inclina la cabeza al lado contrario y vuelve al centro.'],
    commonMistakes: ['Buscar estiramiento fuerte', 'Elevar el hombro', 'Mantener hormigueo persistente'],
    painRule: 'Debe sentirse como tension ligera. Detente si aumenta hormigueo o dolor irradiado.',
  },
  {
    id: 'neck-2',
    name: 'Liberacion suboccipital con respiracion',
    area: 'neck',
    category: 'Liberacion neuromuscular',
    durationSeconds: 40,
    sets: 2,
    reps: '5 respiraciones',
    difficulty: 'Baja',
    description: 'Disminuye tono muscular en la base del craneo para descargar cuello y trapecio.',
    therapeuticGoal: 'Reducir compresion cervical alta y mejorar movilidad sin forzar articulaciones.',
    image: '/exercise-diagrams/suboccipital-release.svg',
    videoDemo: 'neck',
    startingPosition: 'Acostado boca arriba con una toalla enrollada bajo la base del craneo.',
    steps: ['Apoya el peso de la cabeza sobre la toalla.', 'Haz una pequena retraccion de barbilla.', 'Respira lento y deja que el cuello se relaje.'],
    commonMistakes: ['Presionar demasiado', 'Levantar la cabeza', 'Aguantar la respiracion'],
    painRule: 'No debe generar mareo, nausea ni presion intensa.',
  },
  {
    id: 'neck-3',
    name: 'Deslizamiento del nervio ulnar',
    area: 'neck',
    category: 'Neurodinamia',
    durationSeconds: 55,
    sets: 2,
    reps: '6 por lado',
    difficulty: 'Media',
    description: 'Moviliza el trayecto del nervio ulnar cuando hay tension hacia codo, antebrazo o dedos anular y menique.',
    therapeuticGoal: 'Reducir sensacion de atrapamiento neural en cuello-brazo y mejorar movilidad sin irritar el nervio.',
    image: '/exercise-diagrams/median-nerve-glide.svg',
    videoDemo: 'median',
    startingPosition: 'De pie, hombro bajo, brazo al lado del cuerpo y cuello relajado.',
    steps: ['Eleva el brazo lateralmente hasta una posicion comoda.', 'Dobla el codo como si llevaras la mano hacia la oreja.', 'Mantén la muneca suave, sin forzar los dedos.', 'Inclina la cabeza ligeramente al lado contrario.', 'Regresa lento al inicio y repite.'],
    commonMistakes: ['Hacer forma de estiramiento maximo', 'Subir el hombro', 'Provocar hormigueo fuerte'],
    painRule: 'Debe sentirse como tension leve. Detente si aparece corriente hacia mano o dedos.',
  },
  {
    id: 'neck-4',
    name: 'Chin tuck contra pared',
    area: 'neck',
    category: 'Fuerza correctiva',
    durationSeconds: 50,
    sets: 3,
    reps: '8 repeticiones',
    difficulty: 'Baja',
    description: 'Refuerza flexores profundos del cuello para descargar trapecio y mejorar postura cervical.',
    therapeuticGoal: 'Crear soporte activo en cuello para que la liberacion neural se mantenga durante el dia.',
    image: '/exercise-diagrams/suboccipital-release.svg',
    videoDemo: 'neck',
    startingPosition: 'De pie con espalda contra pared, mirada al frente y hombros relajados.',
    steps: ['Apoya suavemente la parte alta de la espalda.', 'Lleva la barbilla hacia atras sin mirar hacia abajo.', 'Mantén dos segundos respirando normal.', 'Relaja a posicion neutra.', 'Repite lento sin apretar mandibula.'],
    commonMistakes: ['Bajar la mirada', 'Empujar cabeza con fuerza', 'Tensar mandibula'],
    painRule: 'Detente si aparece mareo, dolor de cabeza o presion cervical.',
  },
  {
    id: 'shoulders-1',
    name: 'Deslizamiento del nervio radial',
    area: 'shoulders',
    category: 'Neurodinamia',
    durationSeconds: 60,
    sets: 2,
    reps: '8 por lado',
    difficulty: 'Baja',
    description: 'Moviliza el trayecto neural relacionado con cuello, hombro posterior y antebrazo.',
    therapeuticGoal: 'Aliviar irritacion neural que limita elevacion de hombro o genera dolor lateral de brazo.',
    image: '/exercise-diagrams/radial-nerve-glide.svg',
    videoDemo: 'radial',
    startingPosition: 'De pie, brazo al costado, hombro bajo y cuello largo.',
    steps: ['Gira el brazo hacia adentro con pulgar apuntando atras.', 'Flexiona muneca suavemente.', 'Inclina la cabeza al lado contrario y regresa.'],
    commonMistakes: ['Encoger hombros', 'Bloquear el codo con fuerza', 'Provocar hormigueo sostenido'],
    painRule: 'Trabaja con tension suave, nunca con dolor electrico.',
  },
  {
    id: 'shoulders-2',
    name: 'Retracciones escapulares',
    area: 'shoulders',
    category: 'Fuerza correctiva',
    durationSeconds: 50,
    sets: 3,
    reps: '10 repeticiones',
    difficulty: 'Baja',
    description: 'Refuerza la zona escapular para reducir compresion mecanica en cuello y hombro.',
    therapeuticGoal: 'Mejorar soporte muscular para que el tejido neural tenga mas espacio funcional.',
    image: '/exercise-diagrams/scapular-retraction.svg',
    videoDemo: 'scapula',
    startingPosition: 'De pie, brazos al costado.',
    steps: ['Acerca suavemente los omoplatos.', 'Mantén tres segundos.', 'Relaja sin encorvarte.'],
    commonMistakes: ['Arquear espalda baja', 'Subir hombros', 'Apretar con demasiada fuerza'],
    painRule: 'Si sientes pinchazo anterior, reduce rango.',
  },
  {
    id: 'shoulders-3',
    name: 'Wall slide escapular',
    area: 'shoulders',
    category: 'Fuerza correctiva',
    durationSeconds: 60,
    sets: 3,
    reps: '8 repeticiones',
    difficulty: 'Media',
    description: 'Entrena elevacion de hombro con omoplatos estables para disminuir pinzamiento.',
    therapeuticGoal: 'Mejorar espacio funcional del hombro y reforzar control escapular.',
    image: '/exercise-diagrams/scapular-retraction.svg',
    videoDemo: 'scapula',
    startingPosition: 'De pie frente a una pared, antebrazos apoyados y hombros relajados.',
    steps: ['Apoya antebrazos en la pared.', 'Activa abdomen suavemente.', 'Desliza brazos hacia arriba sin subir hombros.', 'Pausa un segundo donde no haya dolor.', 'Baja lento manteniendo omoplatos controlados.'],
    commonMistakes: ['Arquear espalda', 'Encoger hombros', 'Forzar rango con pinchazo'],
    painRule: 'Trabaja solo en rango libre de pinchazo.',
  },
  {
    id: 'shoulders-4',
    name: 'Rotacion externa isometrica',
    area: 'shoulders',
    category: 'Fuerza correctiva',
    durationSeconds: 45,
    sets: 3,
    reps: '5 presiones de 5s',
    difficulty: 'Baja',
    description: 'Activa manguito rotador sin movimiento amplio ni equipo.',
    therapeuticGoal: 'Reforzar estabilidad del hombro para proteger tejido neural y tendones.',
    image: '/exercise-diagrams/radial-nerve-glide.svg',
    videoDemo: 'radial',
    startingPosition: 'De pie junto a una pared, codo flexionado a 90 grados pegado al cuerpo.',
    steps: ['Coloca el dorso de la mano contra la pared.', 'Mantén el codo pegado al costado.', 'Empuja la mano contra la pared sin mover el brazo.', 'Sostén cinco segundos respirando.', 'Relaja y repite.'],
    commonMistakes: ['Separar el codo', 'Torcer el tronco', 'Empujar demasiado fuerte'],
    painRule: 'La activacion debe sentirse muscular, no punzante.',
  },
  {
    id: 'upper-back-1',
    name: 'Apertura toracica con liberacion neural',
    area: 'upper_back',
    category: 'Liberacion neuromuscular',
    durationSeconds: 60,
    sets: 2,
    reps: '8 repeticiones',
    difficulty: 'Baja',
    description: 'Abre la caja toracica y reduce tension protectora en espalda alta.',
    therapeuticGoal: 'Disminuir compresion postural y mejorar movilidad costovertebral.',
    image: '/exercise-diagrams/thoracic-opener.svg',
    videoDemo: 'thoracic',
    startingPosition: 'Sentado con respaldo a la altura media de la espalda.',
    steps: ['Cruza brazos sobre el pecho.', 'Extiende suavemente sobre el respaldo.', 'Regresa con control.'],
    commonMistakes: ['Mover solo el cuello', 'Forzar lumbar', 'Contener la respiracion'],
    painRule: 'Evita dolor punzante o presion intensa.',
  },
  {
    id: 'upper-back-2',
    name: 'Thread the needle controlado',
    area: 'upper_back',
    category: 'Movilidad',
    durationSeconds: 65,
    sets: 2,
    reps: '6 por lado',
    difficulty: 'Baja',
    description: 'Moviliza espalda alta y caja toracica con rotacion suave.',
    therapeuticGoal: 'Reducir rigidez toracica que puede aumentar carga en cuello, hombros y espalda baja.',
    image: '/exercise-diagrams/thoracic-opener.svg',
    videoDemo: 'thoracic',
    startingPosition: 'En cuatro apoyos, manos bajo hombros y rodillas bajo caderas.',
    steps: ['Desliza una mano por debajo del brazo contrario.', 'Gira la espalda alta sin colapsar el cuello.', 'Respira una vez en el rango comodo.', 'Regresa al centro con control.', 'Abre el brazo hacia arriba si no hay dolor.'],
    commonMistakes: ['Rotar desde lumbar', 'Apoyar peso en cuello', 'Ir rapido'],
    painRule: 'Debe sentirse movilidad toracica, no dolor cervical.',
  },
  {
    id: 'upper-back-3',
    name: 'Respiracion costal 360',
    area: 'upper_back',
    category: 'Liberacion neuromuscular',
    durationSeconds: 75,
    sets: 2,
    reps: '6 respiraciones',
    difficulty: 'Baja',
    description: 'Usa respiracion para bajar tono protector de espalda alta y costillas.',
    therapeuticGoal: 'Mejorar expansion toracica y disminuir tension muscular refleja.',
    image: '/exercise-diagrams/thoracic-opener.svg',
    videoDemo: 'thoracic',
    startingPosition: 'Sentado, manos rodeando costillas bajas, hombros sueltos.',
    steps: ['Inhala por nariz expandiendo costillas hacia los lados.', 'Evita subir hombros.', 'Exhala lento por boca como si empañaras un vidrio.', 'Siente que las costillas bajan.', 'Repite manteniendo cuello relajado.'],
    commonMistakes: ['Respirar solo con pecho alto', 'Elevar hombros', 'Forzar inhalacion'],
    painRule: 'Detente si hay mareo o falta de aire.',
  },
  {
    id: 'lower-back-1',
    name: 'Deslizamiento del nervio ciatico',
    area: 'lower_back',
    category: 'Neurodinamia',
    durationSeconds: 60,
    sets: 2,
    reps: '8 por pierna',
    difficulty: 'Baja',
    description: 'Moviliza el nervio ciatico sin mantener estiramientos agresivos.',
    therapeuticGoal: 'Reducir sensacion de compresion lumbar que baja hacia gluteo o pierna.',
    image: '/exercise-diagrams/sciatic-nerve-glide.svg',
    videoDemo: 'sciatic',
    startingPosition: 'Sentado al borde de una silla con espalda alta.',
    steps: ['Estira una rodilla mientras miras al frente.', 'Apunta los dedos del pie hacia ti.', 'Baja la pierna mientras relajas cuello y pie.'],
    commonMistakes: ['Mantener el estiramiento', 'Redondear la espalda', 'Buscar dolor fuerte'],
    painRule: 'No debe dejar dolor residual en pierna despues de la serie.',
  },
  {
    id: 'lower-back-2',
    name: 'Puente corto de descarga lumbar',
    area: 'lower_back',
    category: 'Fuerza correctiva',
    durationSeconds: 55,
    sets: 3,
    reps: '8 repeticiones',
    difficulty: 'Media',
    description: 'Refuerza gluteos para quitar carga repetida de la zona lumbar.',
    therapeuticGoal: 'Mejorar soporte de pelvis y espalda baja despues de liberar tejido neural.',
    image: '/exercise-diagrams/short-bridge.svg',
    videoDemo: 'bridge',
    startingPosition: 'Boca arriba, rodillas flexionadas y pies apoyados.',
    steps: ['Aprieta gluteos suavemente.', 'Eleva cadera hasta alinear tronco.', 'Baja lento vertebra por vertebra.'],
    commonMistakes: ['Hiperextender lumbar', 'Empujar con el cuello', 'Rodillas hacia adentro'],
    painRule: 'Suspende si aumenta dolor lumbar durante la elevacion.',
  },
  {
    id: 'lower-back-3',
    name: 'McGill curl-up modificado',
    area: 'lower_back',
    category: 'Fuerza correctiva',
    durationSeconds: 60,
    sets: 3,
    reps: '6 por lado',
    difficulty: 'Media',
    description: 'Activa core anterior sin flexionar excesivamente la columna lumbar.',
    therapeuticGoal: 'Crear estabilidad lumbar para sostener la liberacion del ciatico y reducir recaidas.',
    image: '/exercise-diagrams/short-bridge.svg',
    videoDemo: 'bridge',
    startingPosition: 'Boca arriba, una rodilla flexionada y una pierna extendida.',
    steps: ['Coloca manos debajo de la zona lumbar.', 'Activa abdomen como si cerraras un cierre.', 'Eleva cabeza y hombros apenas del suelo.', 'Mantén dos segundos sin aplastar manos.', 'Baja lento y cambia pierna.'],
    commonMistakes: ['Hacer abdominal completo', 'Aplanar la espalda baja', 'Tirar del cuello'],
    painRule: 'Debe sentirse abdomen, no espalda baja.',
  },
  {
    id: 'lower-back-4',
    name: 'Bird dog corto',
    area: 'lower_back',
    category: 'Fuerza correctiva',
    durationSeconds: 65,
    sets: 3,
    reps: '6 por lado',
    difficulty: 'Media',
    description: 'Refuerza espalda, gluteos y core con control cruzado.',
    therapeuticGoal: 'Mejorar estabilidad lumbopelvica para disminuir compresiones repetidas.',
    image: '/exercise-diagrams/short-bridge.svg',
    videoDemo: 'bridge',
    startingPosition: 'En cuatro apoyos, espalda neutra y cuello largo.',
    steps: ['Activa abdomen suavemente.', 'Extiende una pierna hacia atras sin arquear la espalda.', 'Agrega brazo contrario solo si mantienes estabilidad.', 'Mantén dos segundos.', 'Regresa lento y alterna.'],
    commonMistakes: ['Arquear lumbar', 'Girar cadera', 'Levantar pierna demasiado alto'],
    painRule: 'Reduce rango si sientes compresion lumbar.',
  },
  {
    id: 'hips-1',
    name: 'Liberacion piriforme asistida',
    area: 'hips',
    category: 'Liberacion neuromuscular',
    durationSeconds: 70,
    sets: 2,
    reps: '6 respiraciones por lado',
    difficulty: 'Media',
    description: 'Relaja musculatura profunda de cadera relacionada con irritacion ciatica.',
    therapeuticGoal: 'Disminuir compresion en gluteo profundo y mejorar rotacion de cadera.',
    image: '/exercise-diagrams/piriformis-release.svg',
    videoDemo: 'piriformis',
    startingPosition: 'Boca arriba, tobillo cruzado sobre la rodilla contraria.',
    steps: ['Acerca la pierna hacia el pecho solo hasta tension suave.', 'Respira lento.', 'Suelta y repite sin rebotes.'],
    commonMistakes: ['Jalar con fuerza', 'Torcer la rodilla', 'Elevar cuello'],
    painRule: 'Debe sentirse en gluteo, no como corriente por la pierna.',
  },
  {
    id: 'hips-2',
    name: '90/90 con inclinacion activa',
    area: 'hips',
    category: 'Movilidad',
    durationSeconds: 70,
    sets: 2,
    reps: '6 por lado',
    difficulty: 'Media',
    description: 'Mejora rotacion interna y externa de cadera sin cargar columna.',
    therapeuticGoal: 'Recuperar movilidad de cadera para que lumbar y rodillas no compensen.',
    image: '/exercise-diagrams/piriformis-release.svg',
    videoDemo: 'piriformis',
    startingPosition: 'Sentado en 90/90, una pierna al frente y otra al lado.',
    steps: ['Alarga la espalda sin rigidez.', 'Inclina el tronco hacia la pierna delantera.', 'Respira una vez en tension suave.', 'Vuelve al centro.', 'Cambia de lado con ayuda de manos si lo necesitas.'],
    commonMistakes: ['Forzar rodilla', 'Redondear mucho espalda', 'Rebotar'],
    painRule: 'La tension debe estar en cadera, nunca en rodilla.',
  },
  {
    id: 'hips-3',
    name: 'Hip airplane asistido',
    area: 'hips',
    category: 'Fuerza correctiva',
    durationSeconds: 60,
    sets: 2,
    reps: '5 por lado',
    difficulty: 'Alta',
    description: 'Entrena control de cadera y gluteo medio con apoyo.',
    therapeuticGoal: 'Mejorar estabilidad lateral para reducir sobrecarga de espalda baja, rodilla y cadera.',
    image: '/exercise-diagrams/piriformis-release.svg',
    videoDemo: 'piriformis',
    startingPosition: 'De pie con una mano en pared o silla estable.',
    steps: ['Apoya peso en una pierna.', 'Inclina el tronco ligeramente hacia adelante.', 'Abre la cadera como si giraras pelvis hacia afuera.', 'Cierra la cadera con control.', 'Mantén rodilla de apoyo alineada.'],
    commonMistakes: ['Perder equilibrio', 'Colapsar rodilla', 'Girar desde la espalda'],
    painRule: 'Hazlo solo con apoyo y sin dolor articular.',
  },
  {
    id: 'knees-1',
    name: 'Deslizamiento femoral suave',
    area: 'knees',
    category: 'Neurodinamia',
    durationSeconds: 50,
    sets: 3,
    reps: '8 por lado',
    difficulty: 'Baja',
    description: 'Moviliza tejido neural anterior del muslo sin comprimir la rodilla.',
    therapeuticGoal: 'Reducir tension anterior de muslo que altera mecanica de rodilla.',
    image: '/exercise-diagrams/femoral-nerve-glide.svg',
    videoDemo: 'femoral',
    startingPosition: 'Acostado de lado, rodillas ligeramente flexionadas.',
    steps: ['Lleva el talon hacia gluteo hasta tension leve.', 'Regresa lentamente.', 'Mantén pelvis estable.'],
    commonMistakes: ['Arquear espalda', 'Jalar fuerte el pie', 'Provocar dolor frontal agudo'],
    painRule: 'No debe aumentar dolor de rodilla ni lumbar.',
  },
  {
    id: 'knees-2',
    name: 'Sentadilla a silla',
    area: 'knees',
    category: 'Fuerza correctiva',
    durationSeconds: 60,
    sets: 3,
    reps: '8 repeticiones',
    difficulty: 'Media',
    description: 'Refuerza cadena de cadera y rodilla para sostener el cambio logrado con liberacion.',
    therapeuticGoal: 'Mejorar tolerancia de carga y control de rodilla en actividades diarias.',
    image: '/exercise-diagrams/chair-squat.svg',
    videoDemo: 'squat',
    startingPosition: 'De pie frente a una silla estable, pies al ancho de cadera.',
    steps: ['Lleva cadera hacia atras.', 'Toca la silla sin desplomarte.', 'Sube empujando el piso.'],
    commonMistakes: ['Rodillas hacia adentro', 'Caer en la silla', 'Levantar talones'],
    painRule: 'Reduce profundidad si el dolor supera 3 de 10.',
  },
  {
    id: 'knees-3',
    name: 'Step-down bajo',
    area: 'knees',
    category: 'Fuerza correctiva',
    durationSeconds: 60,
    sets: 3,
    reps: '6 por lado',
    difficulty: 'Media',
    description: 'Fortalece control de rodilla bajando desde una altura pequena.',
    therapeuticGoal: 'Mejorar control excentrico para escaleras, caminar y sentarse.',
    image: '/exercise-diagrams/chair-squat.svg',
    videoDemo: 'squat',
    startingPosition: 'De pie sobre un escalon bajo o libro firme, con apoyo cerca.',
    steps: ['Apoya todo el pie de la pierna de trabajo.', 'Lleva cadera un poco hacia atras.', 'Baja el talon contrario hacia el suelo.', 'Toca suave sin descargar peso.', 'Sube empujando con la pierna de apoyo.'],
    commonMistakes: ['Rodilla cae hacia adentro', 'Bajar demasiado rapido', 'Usar impulso'],
    painRule: 'Mantén dolor bajo 3 de 10 y usa menor altura si molesta.',
  },
  {
    id: 'knees-4',
    name: 'Spanish squat sin banda',
    area: 'knees',
    category: 'Fuerza correctiva',
    durationSeconds: 45,
    sets: 3,
    reps: '5 pausas de 5s',
    difficulty: 'Media',
    description: 'Isometria de cuadriceps en rango controlado usando una pared como referencia.',
    therapeuticGoal: 'Aumentar tolerancia de tendon/cuadriceps sin movimiento repetitivo doloroso.',
    image: '/exercise-diagrams/chair-squat.svg',
    videoDemo: 'squat',
    startingPosition: 'Espalda cerca de pared, pies al ancho de cadera.',
    steps: ['Desliza espalda apenas hacia abajo.', 'Mantén rodillas alineadas con segundo dedo del pie.', 'Sostén cinco segundos.', 'Sube lento.', 'Descansa y repite.'],
    commonMistakes: ['Bajar demasiado', 'Levantar talones', 'Colapsar rodillas'],
    painRule: 'Debe sentirse esfuerzo muscular, no dolor punzante en rodilla.',
  },
  {
    id: 'ankles-1',
    name: 'Deslizamiento tibial con bombeo de tobillo',
    area: 'ankles',
    category: 'Neurodinamia',
    durationSeconds: 45,
    sets: 2,
    reps: '15 repeticiones',
    difficulty: 'Baja',
    description: 'Combina movilidad de tobillo con deslizamiento neural distal.',
    therapeuticGoal: 'Disminuir rigidez, sensacion de atrapamiento y carga compensatoria en pie/tobillo.',
    image: '/exercise-diagrams/ankle-nerve-glide.svg',
    videoDemo: 'ankle',
    startingPosition: 'Sentado con pierna extendida.',
    steps: ['Apunta los dedos hacia adelante.', 'Lleva los dedos hacia ti.', 'Mantén movimiento suave y continuo.'],
    commonMistakes: ['Mover toda la pierna', 'Hacerlo con dolor agudo', 'Bloquear la rodilla'],
    painRule: 'Debe sentirse como movilidad, no como pinchazo articular.',
  },
  {
    id: 'ankles-2',
    name: 'Rodilla a pared',
    area: 'ankles',
    category: 'Movilidad',
    durationSeconds: 55,
    sets: 2,
    reps: '10 por lado',
    difficulty: 'Baja',
    description: 'Mejora dorsiflexion de tobillo para caminar, sentadilla y escaleras.',
    therapeuticGoal: 'Reducir compensaciones de rodilla y pie al recuperar movilidad de tobillo.',
    image: '/exercise-diagrams/ankle-nerve-glide.svg',
    videoDemo: 'ankle',
    startingPosition: 'De pie frente a pared, pie a pocos centimetros.',
    steps: ['Mantén talon pegado al suelo.', 'Lleva rodilla hacia la pared.', 'Regresa sin levantar arco del pie.', 'Aleja un poco el pie si es facil.', 'Repite lento y controlado.'],
    commonMistakes: ['Levantar talon', 'Colapsar arco', 'Forzar pinchazo delantero'],
    painRule: 'Debe sentirse movilidad, no bloqueo doloroso adelante del tobillo.',
  },
  {
    id: 'ankles-3',
    name: 'Elevacion de talon lenta',
    area: 'ankles',
    category: 'Fuerza correctiva',
    durationSeconds: 50,
    sets: 3,
    reps: '10 repeticiones',
    difficulty: 'Baja',
    description: 'Refuerza pantorrilla y tendon de Aquiles con control.',
    therapeuticGoal: 'Mejorar soporte del tobillo y propulsion al caminar.',
    image: '/exercise-diagrams/ankle-nerve-glide.svg',
    videoDemo: 'ankle',
    startingPosition: 'De pie con manos apoyadas en pared o silla.',
    steps: ['Apoya peso en ambos pies.', 'Eleva talones en dos segundos.', 'Pausa arriba un segundo.', 'Baja en tres segundos.', 'Mantén tobillos alineados.'],
    commonMistakes: ['Caer rapido', 'Girar tobillos hacia afuera', 'Rebotar'],
    painRule: 'Reduce repeticiones si hay dolor en tendon o planta del pie.',
  },
];

export function getExercisesForArea(area: BodyArea, intensity = 5) {
  const exercises = exerciseLibrary.filter((exercise) => exercise.area === area);
  if (intensity >= 8) {
    return exercises.filter((exercise) => exercise.difficulty !== 'Alta').slice(0, 2);
  }
  return exercises.slice(0, 4);
}

export function isBodyArea(value: string | null): value is BodyArea {
  return Boolean(value && Object.prototype.hasOwnProperty.call(areaLabels, value));
}

export function readAssessments(): PainAssessment[] {
  if (typeof window === 'undefined') return [];
  return JSON.parse(window.localStorage.getItem('regenmove.assessments') || '[]');
}

export function saveAssessment(assessment: Omit<PainAssessment, 'id' | 'createdAt'>): PainAssessment {
  const next: PainAssessment = {
    ...assessment,
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
  };
  const assessments = [next, ...readAssessments()].slice(0, 20);
  window.localStorage.setItem('regenmove.assessments', JSON.stringify(assessments));
  return next;
}

export function readProgressLogs(): ProgressLog[] {
  if (typeof window === 'undefined') return [];
  return JSON.parse(window.localStorage.getItem('regenmove.progress') || '[]');
}

export function saveProgressLog(log: Omit<ProgressLog, 'id' | 'createdAt'>): ProgressLog {
  const next: ProgressLog = {
    ...log,
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
  };
  const logs = [next, ...readProgressLogs()].slice(0, 50);
  window.localStorage.setItem('regenmove.progress', JSON.stringify(logs));
  return next;
}
