import type { RegenMoveExerciseDNA } from './types';

export const regenMoveExerciseDNASeed: RegenMoveExerciseDNA[] = [
  {
    id: 'supported-spiral-rib-expansion',
    name: 'Expansion costal espiral con apoyo',
    area: 'upper_back',
    category: 'Respiracion',
    difficulty: 'Baja',
    level: 'level_1_foundation',
    neuralPathways: ['thoracic_intercostal'],
    fascialChains: ['deep_front_line', 'spiral_line', 'functional_front_line'],
    spiralPatterns: ['thoracic_rotation', 'spiral_decompression'],
    breathPatterns: ['360_breathing', 'lateral_rib_expansion', 'spiral_breathing'],
    balanceDomains: ['static_stance', 'weight_shift'],
    instructions: ['Apoya una mano en pared o silla.', 'Eleva el otro brazo en diagonal.', 'Gira suave el torax hacia el brazo elevado.', 'Inhala expandiendo costillas laterales.', 'Exhala alargando la columna.'],
    coachCues: ['No busques amplitud maxima.', 'Busca espacio entre costillas y pelvis.', 'La respiracion guia el movimiento.'],
    painRule: 'No debe provocar mareo, presion toracica ni dolor agudo.',
    durationSeconds: 60,
    seniorSafe: true,
    acutePainSafe: true,
  },
  {
    id: 'tai-chi-spiral-weight-shift',
    name: 'Transferencia espiral tipo Tai Chi',
    area: 'hips',
    category: 'Balance',
    difficulty: 'Media',
    level: 'level_2_integration',
    neuralPathways: ['sciatic', 'femoral'],
    fascialChains: ['spiral_line', 'lateral_line', 'functional_back_line'],
    spiralPatterns: ['tai_chi_weight_shift', 'gait_spiral', 'pelvic_rotation'],
    breathPatterns: ['downregulation_breath', 'spiral_breathing'],
    balanceDomains: ['weight_shift', 'rotational_balance', 'gait_control'],
    instructions: ['De pie con apoyo cerca.', 'Transfiere el peso lentamente de una pierna a la otra.', 'Permite que la pelvis gire ligeramente.', 'Acompaña con brazos suaves en diagonal.', 'Regresa al centro antes de cambiar de lado.'],
    coachCues: ['El peso se mueve lento y estable.', 'La rodilla sigue la linea del pie.', 'No bloquees la respiracion.'],
    painRule: 'Debe sentirse estable. Si hay inseguridad, usa apoyo o reduce amplitud.',
    durationSeconds: 90,
    seniorSafe: true,
    acutePainSafe: false,
  },
  {
    id: 'deep-front-line-hypopressive-prep',
    name: 'Preparacion hipopresiva de linea profunda',
    area: 'lower_back',
    category: 'Respiracion',
    difficulty: 'Media',
    level: 'level_2_integration',
    neuralPathways: ['none_detected'],
    fascialChains: ['deep_front_line', 'diaphragm_pelvic_floor_axis'],
    spiralPatterns: ['spiral_decompression'],
    breathPatterns: ['hypopressive_basic', 'exhale_lengthening'],
    balanceDomains: ['static_stance'],
    instructions: ['Colocate de pie con apoyo estable.', 'Alarga columna y suaviza rodillas.', 'Exhala lentamente sin colapsar pecho.', 'Mantén expansion costal suave.', 'No realices apnea si no estas autorizado.'],
    coachCues: ['Primero postura, luego respiracion.', 'Nunca forzar apnea.', 'Debe sentirse amplio, no comprimido.'],
    painRule: 'No usar si hay mareo, presion, dolor toracico o contraindicacion medica.',
    durationSeconds: 45,
    seniorSafe: false,
    acutePainSafe: false,
  },
];
